options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pydaling-paris:latest", "."]
images:
  - "gcr.io/$PROJECT_ID/pydaling-paris:latest"
